baseURL: "https://lasepri-ous.github.io/" 
title: LASEPri (under construction)
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News & Topics
          url: news/
          weight: 1 
        - name: Books
          url: books/
          weight: 4 
        - name: Papers
          url: papers/
          weight: 3
        - name: Courses
          url: courses/
          weight: 2
	- name: Presentations
          url: presentations/
          weight: 5
        - name: Blog
          url: blog
          weight: 6

params:
    description: "Dummy description."
    author: Dummy Laboratory, Dummy University
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: 動物社会生態学・霊長類学研究室
          subtitle: "当研究室では、霊長類などの中大型哺乳類を中心に、動物の社会のありようをさまざまな観点から理解することを目指します。とくに group living （群居）という現象に着目し、動物たちが共に生きる（共在する）仲間たちとどのように関わり合っているのか、その実態を解明するとともにその進化を論じます。野外調査と動物園での行動観察がメインです。"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:y-takenoshita@ous.ac.jp
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: GitHub
          url: https://github.com/lasepri-ous
        - name: YouTube
          url: https://www.youtube.com/@ous-asepri

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2